### ISSUE TITLE
State and future plans

### ISSUE THREAD

**Issue by filcuc** [dghilardi/RustEditor#1]
What's the state of this plugin? Are you going to push it forward? Why not upstreaming it to the official Qtc repo?

**Comment by dghilardi** [comment]
Hi,
actually this plugin offers completion assist (using racer) and a configuration page in the options window. 
Rudimental highlighting can easily be added using Kate highlight definitions and a new project wizard can be added by copying a couple of files in share/qtcreator/templates/wizards, I didn't include those files in the project because I didn't find yet the way of automate the copy.
I am really interested in this plugin, so I'll continue to develop it, unfortunately right now I am quite busy (work and some other projects...) but I hope to find the time to continue this plugin.
I did not upstream it because I don't think is ready yet...

**Comment by filcuc** [comment]
ok keep up the good work, i'll test it as soon as i find some time. I'm currenlty upstreaming my QtCreator plugin for the Nim programming language 
https://codereview.qt-project.org/#/c/123629/

**Comment by slaufmann** [comment]
Hi,
Actually I would be interested in the files that are needed to enable syntax highlightning and project wizard support. Maybe we could figure something out for the automated install of those files?
I am thinking on using your rusteditor plugin inside of my own plugin. For the automated I would have no problem manually copying files to get it running.
